### ISSUE TITLE
cross_val_score passes a list rather than a DataFrame to Estimator

### ISSUE THREAD

**Issue by cancan101** [paulgb/sklearn-pandas#26] opened 2015-06-16 14:34 UTC
Docs say:
> sklearn-pandas provides a wrapper on sklearn's cross_val_score function which passes a pandas DataFrame to the estimator rather than a numpy array

but I see:
```python
test = pd.DataFrame({'a':[1,2,3]})
class Model(BaseEstimator):
    def fit(self, x):
        print type(x)
    def score(self, x):
        return 1
​
_ = cross_val_score(Model(), test)
```

```python
<type 'list'>
<type 'list'>
<type 'list'>
```

**Comment by cancan101** [comment] 2015-06-16 14:50
The issue is in `_safe_split`:
```
type(_safe_split(Model(), DataWrapper(test), None, [1, 2])[0])
list
```

**Comment by cancan101** [comment] 2015-06-16 14:59
It actually looks like the newest version of scikit handles Dataframes natively.

**Comment by dukebody** [comment] 2015-11-08 16:06
@cancan101 you are probably right regarding your last comment.

Regarding the `cross_val_score` wrapper, it was intended to be able to be able to use a dataframe with the cross-validation functions in pipelines. The list you see is in fact a somewhat dirty trick to avoid sklearn to turn the dataframe into an array. That list is later mapped to a `DataFrame` inside the `DataFrameMapper`. But you cannot use the cv-wrapper directly without the `DataFrameMapper`.

If you want to use a dataframe in cv with old versions of sklearn, simply pass `df.values` to the sklearn cv functions.

I'm closing this because I don't consider it a bug.

**Closed by dukebody** 2015-11-08 16:06 UTC
